# Dependencies
markdown: kramdown

# Metadata
title: Carlos Ferreira Dev Blog
email: dev.carlosferreira@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog with experiences on software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


languages:
  - en
default_lang: en

# Social
twitter:
    username: calbertof
github_username:  jekyll


# SEO
google_site_verification: psDjVdUGM7kPoDMGKfXl5yCKfrFVodSnT1ralFoThiQ
encoding: UTF-8
kramdown:
   input: GFM
   hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-architect
gfm_quirks: paragraph_end
# Build settings

theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
 # - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
